import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Popover, PopoverContent, PopoverTrigger, } from "@/components/ui/popover";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger, } from "@/components/ui/alert-dialog";
import { EllipsisVertical, Pencil, Trash } from "lucide-react";
import { Separator } from "../ui/separator";
import { Link } from "react-router-dom";
const Menu = ({ meal, id, removeMeal }) => {
    return (_jsxs(Popover, { children: [_jsx(PopoverTrigger, { asChild: true, children: _jsx("button", { className: "bg-orange-500 hover:bg-orange-600 active:bg-orange-700 text-white p-2 rounded-sm transition-colors", children: _jsx(EllipsisVertical, {}) }) }), _jsx(PopoverContent, { className: "border-slate-300 overflow-hidden size-fit p-0 shadow-lg", side: "right", align: "start", sideOffset: 12, children: _jsxs("div", { className: "w-[150px]", children: [_jsxs(Link, { className: "flex justify-between font-[600] p-4 hover:bg-orange-500 hover:text-white active:bg-orange-600 transition-colors", to: `/meals/edit/${id}`, children: [_jsx(Pencil, {}), _jsx("span", { children: "Update" })] }), _jsx(Separator, { className: "relative mx-auto w-[85%]" }), _jsxs(AlertDialog, { children: [_jsx(AlertDialogTrigger, { className: "w-full", children: _jsxs("button", { className: "w-full flex justify-between font-[600] hover:bg-red-500 active:bg-red-600 hover:text-white transition-colors p-4", children: [_jsx(Trash, {}), _jsx("span", { children: "Delete" })] }) }), _jsxs(AlertDialogContent, { children: [_jsxs(AlertDialogHeader, { children: [_jsx(AlertDialogTitle, { children: _jsx("h1", { className: "font-bold text-2xl", children: "Are you sure?" }) }), _jsx(AlertDialogDescription, { children: _jsx("p", { className: "text-base", children: "Deleting this meal will permanently remove it from our servers! No changes will be made with the recipes within." }) })] }), _jsxs(AlertDialogFooter, { children: [_jsx(AlertDialogCancel, { children: "Cancel" }), _jsx(AlertDialogAction, { onClick: () => removeMeal(meal), className: "bg-red-500", children: "Continue" })] })] })] })] }) })] }));
};
export default Menu;
